name: CI

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
      - ready_for_review

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Require checkbox all filled
      uses: pione30/checkboxes-all-filled@v1

    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./...

    - name: Lint
      uses: reviewdog/action-golangci-lint@v2
      with:
        reporter: github-pr-review
        fail_on_error: true

    - name: Test
      run: go test -v ./...
