name: CI

on:
  push:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Set up golangci-lint
      run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.42.0

    - name: Build
      run: go build -v ./...

    - name: Lint
      run: golangci-lint run ./...

    - name: Test
      run: go test -v ./...
